#!/usr/bin/env ruby

require 'uri'
require 'json'
require 'httparty'
require 'streamio-ffmpeg'

VIDEO_TYPE = 'video'.freeze
AUDIO_TYPE = 'audio'.freeze

class MediaStatError < StandardError
end

def get_info(path)
  info = FFMPEG::Movie.new(path)

  is_video = !info.video_stream.nil?
  is_audio = info.audio_streams&.any?

  if !is_video && !is_audio
    raise MediaStatError.new('No audio or video detected')
  end

  data = {
    duration: info.duration,
    type: is_video ? VIDEO_TYPE : AUDIO_TYPE,
  }

  data[:fps] = info.frame_rate.to_i if is_video

  puts JSON.dump(data)
end

def main
  uri = URI(ARGV[0].strip)

  case uri.scheme
  when /https?/
    get_info(uri.to_s)
  when 'file'
    get_info(uri.host + uri.path)
  else
    if File.exist?(uri.to_s)
      get_info(uri.to_s)
    else
      raise MediaStatError.new("That type of resource is not handled.")
    end
  end
end

main
